<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Scorebook Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <style type="text/css">
table{
	border-collapse:collapse; 
	outline:black solid thin;
	
	box-shadow: inset 0 14px 10px rgba(255, 255, 255, 0.5), 0 1px 4px rgba(0, 0, 0, 0.25);
	-webkit-box-shadow: inset 0 14px 10px rgba(255, 255, 255, 0.5),
		0 1px 4px rgba(0, 0, 0, 0.25);
	-moz-box-shadow: inset 0 14px 10px rgba(255, 255, 255, 0.5),
		0 1px 4px rgba(0, 0, 0, 0.25);
}
	th{background-color:#E3EAED;border-bottom: 1px solid #333;}
table, td{
	border-bottom:1px dotted #555; 
	color: #000000; padding:3px;
}
	tr.red{background-color:#ff6666;}
	tr.green{background-color:#66ff66;}
	body{color: #444;font: 80%/1 Arial, Helvetica, sans-serif;background: #FFFFFF;}
select.list_select {
	width: 200px;
}
input.btn_submit, select.list_select {
	border: 1px solid #999;
	border-top-color: #CCC;
	border-bottom-color: #666;
	border-radius: 2px;
	-webkit-border-radius: 2px;
	-moz-border-radius: 2px;
	box-shadow: inset 0 14px 10px rgba(255, 255, 255, 0.5), 0 1px 4px rgba(0, 0, 0, 0.25);
	-webkit-box-shadow: inset 0 14px 10px rgba(255, 255, 255, 0.5),
		0 1px 4px rgba(0, 0, 0, 0.25);
	-moz-box-shadow: inset 0 14px 10px rgba(255, 255, 255, 0.5),
		0 1px 4px rgba(0, 0, 0, 0.25);
}
div.element {
	float: center;
	width: 500px;
	background: #F2F9FF;
	border: 1px solid #999;
	margin: 1.5em 0;
	padding: 1.25em 1.25em 0.75em;
	box-shadow: 0 1px 8px rgba(0, 0, 0, 0.25);
	-webkit-box-shadow: 0 1px 8px rgba(0, 0, 0, 0.25);
	-moz-box-shadow: 0 1px 8px rgba(0, 0, 0, 0.25);
}

div.inner_element {
	margin: 1.5em 0;
	padding: 1em 1.25em 0.75em;
	background: #FAFBFC;
	border: 1px solid #AAA;
	box-shadow: 0 1px 8px rgba(0, 0, 0, 0.3);
	-webkit-box-shadow: 0 1px 8px rgba(0, 0, 0, 0.25);
	-moz-box-shadow: 0 1px 8px rgba(0, 0, 0, 0.25);
}
dt {
	float: left;
} 
  </style>

</head>
<body>
<div id="header" class="element" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Scorebook Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'scorebook'),
            'default',
            true) ?>">Scorebook Home</a>
    </div>
</div>
<div class="element">
<p><?php echo $this->layout()->content ?></p>
</div>
<div class="element"><p>&copy; 2011 Vladimir Jotov</p></div>
</body>
</html>